---
#########################################
#            _             _ _          #
#           | |           (_) |         #
#           | | __ ___   ___| | __      #
#       _   | |/ _` \ \ / / | |/ /      #
#      | |__| | (_| |\ V /| |   <       #
#       \____/ \__,_| \_/ |_|_|\_\      #
#                                       #
#########################################

- name: Install keepalived
  ansible.builtin.apt:
    name: keepalived
    state: present
    update_cache: true

- name: Install hcloud-cli
  ansible.builtin.package:
    name: hcloud-cli
    state: present

- name: Copy keepalived configuration
  ansible.builtin.template:
    src: keepalived/keepalived.conf.j2
    dest: /etc/keepalived/keepalived.conf
    owner: root
    group: root
    mode: '0644'
  notify: Restart keepalived

- name: Enable keepalived
  ansible.builtin.systemd:
    name: keepalived
    enabled: true
    state: started
    daemon_reload: yes

