---
- name: Restart networking
  ansible.builtin.systemd_service:
    name: networking
    state: restarted

- name: Restart keepalived
  ansible.builtin.systemd_service:
    name: keepalived
    state: restarted


